sudo: required

language: python
dist: xenial
python: "3.7"

install: pip install -r requirements.txt

# Run tests
script: python setup.py test

# Generate coverage and deploy to `codecov.io`
after_success: python setup.py cov && codecov --token=$CODECOV_TOKEN
