sudo: false

language: python
version:
    - "3.6"

install: pip install codecov pytest-cov

# Run tests
script: python setup.py test

# Generate coverage and deploy to `codecov.io`
after_success: python setup.py test --addopts '--cov=hdrie' && codecov --token=$CODECOV_TOKEN
